name: FTP Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: # Manually trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [v1, v2, v3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify local directory exists
        run: |
          if [ ! -d "${{ matrix.version }}" ]; then
            echo "Directory ${{ matrix.version }} does not exist."
            exit 1
          fi

      - name: List contents of the local directory
        run: ls -la ${{ matrix.version }}

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ${{ matrix.version }}
          remote-dir: /sabin-maharjan.com.np/${{ matrix.version }}
          git-ftp-args: --mkdir
